// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVeDqTHqppIBxx_PDvdAFQzn6GT3tG_ME',
    appId: '1:282295694957:android:c3bd604b12db2472b2f164',
    messagingSenderId: '282295694957',
    projectId: 'vail-clean',
    storageBucket: 'vail-clean.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2gvyRBWSFV25aVHb3DMRiX9G64L4hfbU',
    appId: '1:282295694957:ios:bbcad302bc824697b2f164',
    messagingSenderId: '282295694957',
    projectId: 'vail-clean',
    storageBucket: 'vail-clean.firebasestorage.app',
    iosBundleId: 'com.example.veilClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbkmB0u30OsVnNESQ2HSlPqj3ajPlEGf4',
    appId: '1:282295694957:web:0c52a76650f596eeb2f164',
    messagingSenderId: '282295694957',
    projectId: 'vail-clean',
    authDomain: 'vail-clean.firebaseapp.com',
    storageBucket: 'vail-clean.firebasestorage.app',
    measurementId: 'G-7MYBGLVMS0',
  );
}
